# Plugins
plugins:
  - jekyll-remote-theme

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0

# Author settings
author: "Arseniy Karmanov"

markdown: CommonMarkGhPages

commonmark:
  options: ["SMART", "FOOTNOTES", "STRIKETHROUGH_DOUBLE_TILDE"]
  extensions: ["table", "strikethrough", "autolink", "tasklist", "footnote", "definition-list", "heading-permalink"]

github:
  is_project_page: false
  is_user_page: false
  is_organization_page: false